### ISSUE TITLE
Error: Route [object Object] does not exist

### ISSUE THREAD

**Issue by bitttttten** [nareshbhatia/mobx-state-router#37]
Using `v8.9.1` and building as a commonjs2 module. Using hapi to host my server. When running my app (`node server/index.js`) then access it, I get this error message which comes from [here](https://github.com/nareshbhatia/mobx-state-router/blob/master/src/router-store.ts#L109-L112).

```
Error: Route [object Object] does not exist
    at RouterStore.module.exports../node_modules/mobx-state-router/dist/router-store.js.RouterStore.getRoute (build\\server\\main.js:2839:9)
    at RouterStore.module.exports../node_modules/mobx-state-router/dist/router-store.js.RouterStore.transition (build\\server\\main.js:2873:17)
    at RouterStore.module.exports../node_modules/mobx-state-router/dist/router-store.js.RouterStore.goTo (build\\server\\main.js:2826:15)
    at StaticAdapter.goToLocation (node_modules\\mobx-state-router\\dist\\adapters\\static-adapter.js:32:42)
    at web (server\\controllers\\web.js:30:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

If I log out the values above the check of `toStateOrRouteName instanceof RouterState`:

```

    goTo(
        toStateOrRouteName: RouterState | string,
        params: StringMap = {},
        queryParams: Object = {}
    ): Promise<RouterState> {
        console.log(toStateOrRouteName); // logs out `RouterState { routeName: 'home', params: {}, queryParams: {} }`
        console.log(toStateOrRouteName instanceof RouterState); // logs out `false`
        const toState =
            toStateOrRouteName instanceof RouterState
                ? toStateOrRouteName
                : new RouterState(toStateOrRouteName, params, queryParams);
```

So it looks like it is an instance of RouterState although it is returning false? Which is confusing.

My server code looks a bit like:

```
		const { StaticAdapter } = require('mobx-state-router')
		const { createLocation } = require('history')
		const Loadable = require('react-loadable')

		...

		await Loadable.preloadAll()
		const rootStore = new RootStore({}, routes)
		const staticAdapter = new StaticAdapter(rootStore.routerStore)
		const locationInstance = createLocation(location)
		await staticAdapter.goToLocation(locationInstance)
```

And this is where it errors. I could share more code if necessary.

**Comment by nareshbhatia** [comment]
Hmmm, it is definitely confusing. Sometimes you can get a clue of what's going wrong by looking at the router logs before the error occurs. For that you have to run the app (or server in your case) in debug mode.

If that does not help, you may want to create a minimal app that reproduces the error. With that we may be able to help.

**Comment by bitttttten** [comment]
Before it crashes I see this when running it in debug mode:

```
StaticAdapter.goToLocation({"pathname":"/","search":"","hash":""})
RouterStore.transition({"routeName":"__initial__","params":{},"queryParams":{}}, {"routeName":{"routeName":"home","params":{},"queryParams":{}},"params":{},"queryParams":{}})
```

So again you can see here that routeName consists of an object (an instance of RouterStore, I assume). I also built it with node v10.

The repo is on gitlab, it's a private repo at the moment. Do you have an account there? I can share it with you. Unless you would prefer it a different way.

**Comment by nareshbhatia** [comment]
Sure, let me see what I can do. I am `nareshbhatia` on gitlab.

**Comment by bitttttten** [comment]
Great thanks. I was thinking this is a problem with my babel config and not related to the library.

**Comment by bitttttten** [comment]
I changed the check to pass if it's an object, although now I run into another error 😅 

```
$ node server/index.js
RouterStore.transition({"routeName":"__initial__","params":{},"queryParams":{}}, {"routeName":"home","params":{},"queryParams":{}})
Unhandled Promise rejection:
TypeError: a.valueOf is not a function
    at valueEqual (node_modules\value-equal\cjs\index.js:24:20)
    at node_modules\value-equal\cjs\index.js:35:14
    at Array.every (<anonymous>)
    at Object.valueEqual [as default] (node_modules\value-equal\cjs\index.js:34:18)
    at RouterState.isEqual (node_modules\mobx-state-router\dist\router-store.js:34:37)
    at RouterLink.module.exports../node_modules/mobx-state-router/dist/components/router-link.js.RouterLink.render (build\server\main.js:2637:48)
    at RouterLink.makeComponentReactive (node_modules\mobx-react\index.js:749:56)
    at RouterLink.target.render (node_modules\mobx-react\index.js:971:38)
    at d (node_modules\react-dom\cjs\react-dom-server.node.production.min.js:28:211)
    at xa (node_modules\react-dom\cjs\react-dom-server.node.production.min.js:28:493)
error Command failed with exit code 1.
```

I also copied your example webpack config and now I am really stumpted. On the client it works fine! It is only when I run this in node.

**Comment by nareshbhatia** [comment]
I spent some time understanding your setup yesterday. Will be able to spend a couple of hours today.

**Comment by nareshbhatia** [comment]
Reopening. I fixed your first issue by changing the check from `instanceof` to `typeof`, but now I am hitting your second issue: `a.valueOf is not a function`. Still looking. Amazing that this has never been a problem on the client side.

**Comment by nareshbhatia** [comment]
FWIW, this seems to be the last issue. If I comment  out part of the `valueEqual` method, the app actually comes up. Will look at it tomorrow.

**Comment by bitttttten** [comment]
It's a shame to change the check into typeof string check, since the previous solution was a lot more elegant and clear. I'm also suprised that nobody has hit this issue before 😅

**Comment by bitttttten** [comment]
That's a shame. I updated my app to the new version and it works!

Thank you so much for the update. I am really liking this library so far, my favourite implementatation of the seperating state and ui 👍

**Comment by nareshbhatia** [comment]
Glad you are liking it :-)
