### ISSUE TITLE
How to debug "toState is not defined"

### ISSUE THREAD

**Issue by bitttttten** [nareshbhatia/mobx-state-router#46]
```
Error: toState is undefined
    at RouterStore.<anonymous> (node_modules\mobx-state-router\dist\router-store.js:198:31)
    at step (node_modules\mobx-state-router\dist\router-store.js:38:23)
    at Object.throw (node_modules\mobx-state-router\dist\router-store.js:19:53)
    at rejected (node_modules\mobx-state-router\dist\router-store.js:11:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I am recieving this error in my server and I am not sure how to debug it. Am I perhaps missing a try catch? I am guessing it's an error in my routes for some reason.

**Comment by bitttttten** [comment]
I see now I can use the setErrorHook hook to catch my errors.

**Comment by bitttttten** [comment]
`rootStore.routerStore.setErrorHook((error) => {
	errorLogginService(error) // eslint-disable-line no-console
})`
